//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaUnidadAdm
    {
        public int relacionAreaUA { get; set; }
        public int catAreaID { get; set; }
        public int catUnidadAdmID { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual CatArea CatArea { get; set; }
        public virtual CatUnidadAdm CatUnidadAdm { get; set; }
    }
}
