//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatDocumento
    {
        public CatDocumento()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int catDocumentoID { get; set; }
        public int catSolicitudID { get; set; }
        public string descripcion { get; set; }
        public string prefijo { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual CatSolicitud CatSolicitud { get; set; }
    }
}
