//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEntidadFederativa
    {
        public CatEntidadFederativa()
        {
            this.CatDestino = new HashSet<CatDestino>();
            this.CatMunicipio = new HashSet<CatMunicipio>();
            this.GastoCorriente = new HashSet<GastoCorriente>();
            this.LugarSolicitudRecurso = new HashSet<LugarSolicitudRecurso>();
        }
    
        public int catEntidadFederativaID { get; set; }
        public int catPaisID { get; set; }
        public string descripcion { get; set; }
        public string abreviatura { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<CatDestino> CatDestino { get; set; }
        public virtual CatPais CatPais { get; set; }
        public virtual ICollection<CatMunicipio> CatMunicipio { get; set; }
        public virtual ICollection<GastoCorriente> GastoCorriente { get; set; }
        public virtual ICollection<LugarSolicitudRecurso> LugarSolicitudRecurso { get; set; }
    }
}
