//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEstatusSolicitud
    {
        public CatEstatusSolicitud()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.EstatusAccion = new HashSet<EstatusAccion>();
            this.EstatusPerfil = new HashSet<EstatusPerfil>();
            this.SolicitudRecurso = new HashSet<SolicitudRecurso>();
        }
    
        public short catEstatusSolicitudID { get; set; }
        public string descripcion { get; set; }
        public string descripcionCorta { get; set; }
        public Nullable<int> estatusSiguiente { get; set; }
        public Nullable<int> estatusDevolucion { get; set; }
        public Nullable<int> estatusAlternativo { get; set; }
        public Nullable<int> estatusAltDev { get; set; }
        public bool estatusLogico { get; set; }
        public Nullable<int> catAreaID { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual CatArea CatArea { get; set; }
        public virtual ICollection<EstatusAccion> EstatusAccion { get; set; }
        public virtual ICollection<EstatusPerfil> EstatusPerfil { get; set; }
        public virtual ICollection<SolicitudRecurso> SolicitudRecurso { get; set; }
    }
}
