//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMunicipio
    {
        public CatMunicipio()
        {
            this.LugarSolicitudRecurso = new HashSet<LugarSolicitudRecurso>();
        }
    
        public int catMunicipioID { get; set; }
        public int catEntidadFederativaID { get; set; }
        public string descripcion { get; set; }
        public bool masEconomico { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual CatEntidadFederativa CatEntidadFederativa { get; set; }
        public virtual ICollection<LugarSolicitudRecurso> LugarSolicitudRecurso { get; set; }
    }
}
