//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatModulo
    {
        public CatModulo()
        {
            this.CatEvento = new HashSet<CatEvento>();
            this.ModuloSubmodulo = new HashSet<ModuloSubmodulo>();
            this.Parametro = new HashSet<Parametro>();
            this.PerfilModulo = new HashSet<PerfilModulo>();
        }
    
        public int catModuloID { get; set; }
        public string descripcion { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<CatEvento> CatEvento { get; set; }
        public virtual ICollection<ModuloSubmodulo> ModuloSubmodulo { get; set; }
        public virtual ICollection<Parametro> Parametro { get; set; }
        public virtual ICollection<PerfilModulo> PerfilModulo { get; set; }
    }
}
