//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPago
    {
        public CatPago()
        {
            this.MovimientoAdministrativo = new HashSet<MovimientoAdministrativo>();
        }
    
        public int catPagoID { get; set; }
        public string descripcion { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<MovimientoAdministrativo> MovimientoAdministrativo { get; set; }
    }
}
