//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPartida
    {
        public CatPartida()
        {
            this.Agregaduria = new HashSet<Agregaduria>();
            this.Beca = new HashSet<Beca>();
            this.Becalos = new HashSet<Becalos>();
            this.GastoCorriente = new HashSet<GastoCorriente>();
            this.GastoAduana = new HashSet<GastoAduana>();
            this.GastoFunerario = new HashSet<GastoFunerario>();
            this.ImpuestoSobreNomina = new HashSet<ImpuestoSobreNomina>();
            this.Laudo = new HashSet<Laudo>();
            this.PartidaSolicitudRecurso = new HashSet<PartidaSolicitudRecurso>();
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public int catPartidaID { get; set; }
        public Nullable<int> catSolicitudID { get; set; }
        public int capitulo { get; set; }
        public Nullable<int> concepto { get; set; }
        public string denominacion { get; set; }
        public string descripcion { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<Agregaduria> Agregaduria { get; set; }
        public virtual ICollection<Beca> Beca { get; set; }
        public virtual ICollection<Becalos> Becalos { get; set; }
        public virtual ICollection<GastoCorriente> GastoCorriente { get; set; }
        public virtual ICollection<GastoAduana> GastoAduana { get; set; }
        public virtual ICollection<GastoFunerario> GastoFunerario { get; set; }
        public virtual ICollection<ImpuestoSobreNomina> ImpuestoSobreNomina { get; set; }
        public virtual ICollection<Laudo> Laudo { get; set; }
        public virtual ICollection<PartidaSolicitudRecurso> PartidaSolicitudRecurso { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual CatSolicitud CatSolicitud { get; set; }
    }
}
