//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatSolicitud
    {
        public CatSolicitud()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
            this.CatConceptoGasto = new HashSet<CatConceptoGasto>();
            this.CatDocumento = new HashSet<CatDocumento>();
            this.CatPartida = new HashSet<CatPartida>();
            this.SolicitudCatUnidadAdm = new HashSet<SolicitudCatUnidadAdm>();
            this.SolicitudRecurso = new HashSet<SolicitudRecurso>();
            this.TipoSolicitudPorArea = new HashSet<TipoSolicitudPorArea>();
            this.TipoSolicitudPorUA = new HashSet<TipoSolicitudPorUA>();
        }
    
        public int catSolicitudID { get; set; }
        public int tipoSolicitudControlCod { get; set; }
        public string descripcion { get; set; }
        public string areaPago { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        public virtual ICollection<CatConceptoGasto> CatConceptoGasto { get; set; }
        public virtual ICollection<CatDocumento> CatDocumento { get; set; }
        public virtual ICollection<CatPartida> CatPartida { get; set; }
        public virtual ICollection<SolicitudCatUnidadAdm> SolicitudCatUnidadAdm { get; set; }
        public virtual ICollection<SolicitudRecurso> SolicitudRecurso { get; set; }
        public virtual ICollection<TipoSolicitudPorArea> TipoSolicitudPorArea { get; set; }
        public virtual ICollection<TipoSolicitudPorUA> TipoSolicitudPorUA { get; set; }
    }
}
