//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laudo
    {
        public int laudoID { get; set; }
        public int solicitudRecursoID { get; set; }
        public int catConceptoGastoID { get; set; }
        public int catPartidaID { get; set; }
        public string numeroExpediente { get; set; }
        public decimal importe { get; set; }
        public Nullable<bool> estatusLogico { get; set; }
    
        public virtual CatConceptoGasto CatConceptoGasto { get; set; }
        public virtual CatPartida CatPartida { get; set; }
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
    }
}
