//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LugarSolicitudRecurso
    {
        public int lugarSolicitudRecursoID { get; set; }
        public int detalleSolicitudRecursoID { get; set; }
        public int catMonedaID { get; set; }
        public int catPaisID { get; set; }
        public Nullable<int> catEntidadFederativaID { get; set; }
        public Nullable<int> catMunicipioID { get; set; }
        public Nullable<int> catDestinoID { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int diasCompletos { get; set; }
        public int diasMedios { get; set; }
        public decimal importeOtorgado { get; set; }
        public decimal tipoCambio { get; set; }
    
        public virtual CatDestino CatDestino { get; set; }
        public virtual CatEntidadFederativa CatEntidadFederativa { get; set; }
        public virtual CatMoneda CatMoneda { get; set; }
        public virtual CatMunicipio CatMunicipio { get; set; }
        public virtual CatPais CatPais { get; set; }
        public virtual DetalleSolicitudRecurso DetalleSolicitudRecurso { get; set; }
    }
}
