//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoAdministrativo
    {
        public MovimientoAdministrativo()
        {
            this.PagoCheque = new HashSet<PagoCheque>();
            this.TransferenciaBancaria = new HashSet<TransferenciaBancaria>();
        }
    
        public int movimientoAdministrativoID { get; set; }
        public int solicitudRecursoID { get; set; }
        public int catPagoID { get; set; }
        public int presionGastoID { get; set; }
        public int catCuentaID { get; set; }
        public string descripcionPago { get; set; }
        public decimal montoTotalSolicitud { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual CatCuenta CatCuenta { get; set; }
        public virtual CatPago CatPago { get; set; }
        public virtual PresionGasto PresionGasto { get; set; }
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
        public virtual ICollection<PagoCheque> PagoCheque { get; set; }
        public virtual ICollection<TransferenciaBancaria> TransferenciaBancaria { get; set; }
    }
}
