//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalizacion
    {
        public int penalizacionID { get; set; }
        public int proveedorID { get; set; }
        public int catMonedaID { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> retIVA { get; set; }
        public decimal tipoDeCambio { get; set; }
        public Nullable<decimal> total { get; set; }
        public bool aplica { get; set; }
    
        public virtual CatMoneda CatMoneda { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
