//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilModulo
    {
        public int perfilModuloID { get; set; }
        public int catPerfilID { get; set; }
        public int catModuloID { get; set; }
    
        public virtual CatModulo CatModulo { get; set; }
        public virtual CatPerfil CatPerfil { get; set; }
    }
}
