//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresionGasto
    {
        public PresionGasto()
        {
            this.MovimientoAdministrativo = new HashSet<MovimientoAdministrativo>();
        }
    
        public int presionGastoID { get; set; }
        public short catEstausPresionID { get; set; }
        public int folioPresion { get; set; }
        public System.DateTime fechaPresion { get; set; }
    
        public virtual CatEstatusPresion CatEstatusPresion { get; set; }
        public virtual ICollection<MovimientoAdministrativo> MovimientoAdministrativo { get; set; }
    }
}
