//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroVolante
    {
        public int registroVolanteID { get; set; }
        public int solicitudRecursoID { get; set; }
        public string area { get; set; }
        public string tipoDeGasto { get; set; }
        public Nullable<decimal> importeDevuelto { get; set; }
        public string fechaRecepcion { get; set; }
        public string fechaElaboracion { get; set; }
        public string tipoMoneda { get; set; }
        public int numeroVolante { get; set; }
        public string folio { get; set; }
        public string oficio { get; set; }
        public string motivoDevolucion { get; set; }
        public Nullable<decimal> tipoDeCambio { get; set; }
        public int anioComprobado { get; set; }
        public System.DateTime fechaGeneracionVolante { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
    }
}
