//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudRecurso
    {
        public SolicitudRecurso()
        {
            this.Agregaduria = new HashSet<Agregaduria>();
            this.Asignacion = new HashSet<Asignacion>();
            this.Beca = new HashSet<Beca>();
            this.Becalos = new HashSet<Becalos>();
            this.Bitacora = new HashSet<Bitacora>();
            this.CargaCuotaDiaria = new HashSet<CargaCuotaDiaria>();
            this.DetalleSolicitudRecurso = new HashSet<DetalleSolicitudRecurso>();
            this.Documento = new HashSet<Documento>();
            this.EstatusMovimiento = new HashSet<EstatusMovimiento>();
            this.FirmaElectronica = new HashSet<FirmaElectronica>();
            this.GastoAduana = new HashSet<GastoAduana>();
            this.GastoCorriente = new HashSet<GastoCorriente>();
            this.GastoFunerario = new HashSet<GastoFunerario>();
            this.ImpuestoSobreNomina = new HashSet<ImpuestoSobreNomina>();
            this.Laudo = new HashSet<Laudo>();
            this.MovimientoAdministrativo = new HashSet<MovimientoAdministrativo>();
            this.PresupuestoClc = new HashSet<PresupuestoClc>();
            this.Proveedor = new HashSet<Proveedor>();
            this.RegistroContable = new HashSet<RegistroContable>();
            this.RegistroVolante = new HashSet<RegistroVolante>();
            this.SolicitudFirma = new HashSet<SolicitudFirma>();
        }
    
        public int solicitudRecursoID { get; set; }
        public int catSolicitudID { get; set; }
        public int catPrioridadID { get; set; }
        public int catUnidadAdmID { get; set; }
        public short catEstatusSolicitudID { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public string observaciones { get; set; }
        public string oficioSolicitud { get; set; }
        public System.DateTime fechaControl { get; set; }
        public System.DateTime fechaActualizacion { get; set; }
        public Nullable<int> catEventoID { get; set; }
        public string folioSolicitud { get; set; }
        public int catFormaComprobacionID { get; set; }
    
        public virtual ICollection<Agregaduria> Agregaduria { get; set; }
        public virtual ICollection<Asignacion> Asignacion { get; set; }
        public virtual ICollection<Beca> Beca { get; set; }
        public virtual ICollection<Becalos> Becalos { get; set; }
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ICollection<CargaCuotaDiaria> CargaCuotaDiaria { get; set; }
        public virtual CatEstatusSolicitud CatEstatusSolicitud { get; set; }
        public virtual CatEvento CatEvento { get; set; }
        public virtual CatFormaComprobacion CatFormaComprobacion { get; set; }
        public virtual CatPrioridad CatPrioridad { get; set; }
        public virtual CatSolicitud CatSolicitud { get; set; }
        public virtual CatUnidadAdm CatUnidadAdm { get; set; }
        public virtual ICollection<DetalleSolicitudRecurso> DetalleSolicitudRecurso { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<EstatusMovimiento> EstatusMovimiento { get; set; }
        public virtual ICollection<FirmaElectronica> FirmaElectronica { get; set; }
        public virtual ICollection<GastoAduana> GastoAduana { get; set; }
        public virtual ICollection<GastoCorriente> GastoCorriente { get; set; }
        public virtual ICollection<GastoFunerario> GastoFunerario { get; set; }
        public virtual ICollection<ImpuestoSobreNomina> ImpuestoSobreNomina { get; set; }
        public virtual ICollection<Laudo> Laudo { get; set; }
        public virtual ICollection<MovimientoAdministrativo> MovimientoAdministrativo { get; set; }
        public virtual ICollection<PresupuestoClc> PresupuestoClc { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<RegistroContable> RegistroContable { get; set; }
        public virtual ICollection<RegistroVolante> RegistroVolante { get; set; }
        public virtual ICollection<SolicitudFirma> SolicitudFirma { get; set; }
    }
}
