//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSolicitudPorArea
    {
        public int tipoSolicitudPorAreaConfigID { get; set; }
        public int catAreaID { get; set; }
        public int catSolicitudID { get; set; }
        public int catRegionID { get; set; }
    
        public virtual CatArea CatArea { get; set; }
        public virtual CatRegion CatRegion { get; set; }
        public virtual CatSolicitud CatSolicitud { get; set; }
    }
}
