//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoJefeDepto
    {
        public int TipoJefeDeptoID { get; set; }
        public int usuarioID { get; set; }
        public int catJefeDeptoID { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual CatJefeDepto CatJefeDepto { get; set; }
    }
}
