//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferenciaBancaria
    {
        public int transferenciaBancariaID { get; set; }
        public int movimientoAdministrativoID { get; set; }
        public short catEstatusPagoID { get; set; }
        public System.DateTime fechaPago { get; set; }
        public string beneficiario { get; set; }
        public string cuentaClabe { get; set; }
        public decimal montoPago { get; set; }
        public string banco { get; set; }
        public string numeroTransferencia { get; set; }
        public string concepto { get; set; }
        public string numeroExpediente { get; set; }
    
        public virtual CatEstatusPago CatEstatusPago { get; set; }
        public virtual MovimientoAdministrativo MovimientoAdministrativo { get; set; }
    }
}
