//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Asignacion = new HashSet<Asignacion>();
            this.Bitacora = new HashSet<Bitacora>();
            this.EstatusMovimiento = new HashSet<EstatusMovimiento>();
            this.LogError = new HashSet<LogError>();
            this.UsuarioRegionFiscalizacion = new HashSet<UsuarioRegionFiscalizacion>();
        }
    
        public int usuarioID { get; set; }
        public int catUnidadAdmID { get; set; }
        public int catPerfilID { get; set; }
        public string cuenta { get; set; }
        public string correo { get; set; }
        public int numeroExpediente { get; set; }
        public bool estatusLogico { get; set; }
        public int catRolID { get; set; }
    
        public virtual ICollection<Asignacion> Asignacion { get; set; }
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual CatPerfil CatPerfil { get; set; }
        public virtual CatPerfil CatPerfil1 { get; set; }
        public virtual CatRol CatRol { get; set; }
        public virtual CatUnidadAdm CatUnidadAdm { get; set; }
        public virtual ICollection<EstatusMovimiento> EstatusMovimiento { get; set; }
        public virtual ICollection<LogError> LogError { get; set; }
        public virtual ICollection<UsuarioRegionFiscalizacion> UsuarioRegionFiscalizacion { get; set; }
    }
}
