//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDatosIntegrante
    {
        public int expediente { get; set; }
        public string grado { get; set; }
        public string cargo { get; set; }
        public string nombre { get; set; }
        public string RFC { get; set; }
        public int codAdscripcion { get; set; }
        public string Adscripcion { get; set; }
        public string codCentroDistribucion { get; set; }
        public string enlaceID { get; set; }
        public int codEstatusIntegrante { get; set; }
        public string descripcionEstatusIntegrante { get; set; }
    }
}
