//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDependientesIntegrante
    {
        public int dependienteID { get; set; }
        public Nullable<int> expediente { get; set; }
        public short tipoDependienteID { get; set; }
        public string descripcionTipoDependiente { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string sexo { get; set; }
    }
}
