//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beca
    {
        public int BecaID { get; set; }
        public int solicitudRecursoID { get; set; }
        public int catAcademiaID { get; set; }
        public int catPartidaID { get; set; }
        public string generacion { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public string rfc { get; set; }
        public string nombre { get; set; }
        public int numeroFaltas { get; set; }
        public decimal montoDepositar { get; set; }
        public string institucionBancaria { get; set; }
        public string clabeInterbancaria { get; set; }
        public string cuentaBancaria { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual CatAcademia CatAcademia { get; set; }
        public virtual CatPartida CatPartida { get; set; }
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
    }
}
