//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int bitacoraID { get; set; }
        public int solicitudRecursoID { get; set; }
        public short catEstatusSolicitudID { get; set; }
        public int usuarioID { get; set; }
        public System.DateTime fecha { get; set; }
        public string modulo { get; set; }
        public string evento { get; set; }
    
        public virtual CatEstatusSolicitud CatEstatusSolicitud { get; set; }
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
