//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatArea
    {
        public CatArea()
        {
            this.AreaUnidadAdm = new HashSet<AreaUnidadAdm>();
            this.CatEstatusSolicitud = new HashSet<CatEstatusSolicitud>();
            this.TipoSolicitudPorArea = new HashSet<TipoSolicitudPorArea>();
        }
    
        public int catAreaID { get; set; }
        public string descripcion { get; set; }
        public bool estatusLogico { get; set; }
        public Nullable<int> areaPadre { get; set; }
    
        public virtual ICollection<AreaUnidadAdm> AreaUnidadAdm { get; set; }
        public virtual ICollection<CatEstatusSolicitud> CatEstatusSolicitud { get; set; }
        public virtual ICollection<TipoSolicitudPorArea> TipoSolicitudPorArea { get; set; }
    }
}
