//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatBanco
    {
        public CatBanco()
        {
            this.DetalleSolicitudRecurso = new HashSet<DetalleSolicitudRecurso>();
            this.CatCuenta = new HashSet<CatCuenta>();
        }
    
        public int catBancoID { get; set; }
        public string descripcion { get; set; }
        public bool estatusLogico { get; set; }
        public string cveBanco { get; set; }
    
        public virtual ICollection<DetalleSolicitudRecurso> DetalleSolicitudRecurso { get; set; }
        public virtual ICollection<CatCuenta> CatCuenta { get; set; }
    }
}
