//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCuenta
    {
        public CatCuenta()
        {
            this.MovimientoAdministrativo = new HashSet<MovimientoAdministrativo>();
            this.MovimientoBancario = new HashSet<MovimientoBancario>();
        }
    
        public int catCuentaID { get; set; }
        public int catBancoID { get; set; }
        public string descripcion { get; set; }
        public string numeroCuenta { get; set; }
        public string areaBanco { get; set; }
        public int anio { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual CatBanco CatBanco { get; set; }
        public virtual ICollection<MovimientoAdministrativo> MovimientoAdministrativo { get; set; }
        public virtual ICollection<MovimientoBancario> MovimientoBancario { get; set; }
    }
}
