//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatDestino
    {
        public CatDestino()
        {
            this.GastoCorriente = new HashSet<GastoCorriente>();
            this.LugarSolicitudRecurso = new HashSet<LugarSolicitudRecurso>();
        }
    
        public int catDestinoID { get; set; }
        public int catEntidadFederativaID { get; set; }
        public string descripcion { get; set; }
        public bool estatusLogico { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual CatEntidadFederativa CatEntidadFederativa { get; set; }
        public virtual ICollection<GastoCorriente> GastoCorriente { get; set; }
        public virtual ICollection<LugarSolicitudRecurso> LugarSolicitudRecurso { get; set; }
    }
}
