//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEvento
    {
        public CatEvento()
        {
            this.SolicitudRecurso = new HashSet<SolicitudRecurso>();
        }
    
        public int catEventoID { get; set; }
        public string cveEvento { get; set; }
        public string descripcion { get; set; }
        public string descLargaEvento { get; set; }
        public int catModuloID { get; set; }
        public int catPerfilID { get; set; }
        public bool estatusLogico { get; set; }
        public int catEventoAccionID { get; set; }
    
        public virtual CatEventoAccion CatEventoAccion { get; set; }
        public virtual CatModulo CatModulo { get; set; }
        public virtual CatPerfil CatPerfil { get; set; }
        public virtual ICollection<SolicitudRecurso> SolicitudRecurso { get; set; }
    }
}
