//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatFormaComprobacion
    {
        public CatFormaComprobacion()
        {
            this.SolicitudRecurso = new HashSet<SolicitudRecurso>();
        }
    
        public int catFormaComprobacionID { get; set; }
        public string FormaComprobacion { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<SolicitudRecurso> SolicitudRecurso { get; set; }
    }
}
