//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMoneda
    {
        public CatMoneda()
        {
            this.Agregaduria = new HashSet<Agregaduria>();
            this.Factura = new HashSet<Factura>();
            this.LugarSolicitudRecurso = new HashSet<LugarSolicitudRecurso>();
            this.Penalizacion = new HashSet<Penalizacion>();
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public int catMonedaID { get; set; }
        public string descripcion { get; set; }
        public string codigo { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<Agregaduria> Agregaduria { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<LugarSolicitudRecurso> LugarSolicitudRecurso { get; set; }
        public virtual ICollection<Penalizacion> Penalizacion { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}
