//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPerfil
    {
        public CatPerfil()
        {
            this.CatEvento = new HashSet<CatEvento>();
            this.PerfilModulo = new HashSet<PerfilModulo>();
            this.EstatusPerfil = new HashSet<EstatusPerfil>();
            this.Usuario = new HashSet<Usuario>();
            this.Usuario1 = new HashSet<Usuario>();
        }
    
        public int catPerfilID { get; set; }
        public string descripcion { get; set; }
        public string descripcionCorta { get; set; }
        public Nullable<short> perfilAnalistaID { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<CatEvento> CatEvento { get; set; }
        public virtual ICollection<PerfilModulo> PerfilModulo { get; set; }
        public virtual ICollection<EstatusPerfil> EstatusPerfil { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
    }
}
