//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPais
    {
        public CatPais()
        {
            this.Agregaduria = new HashSet<Agregaduria>();
            this.CatEntidadFederativa = new HashSet<CatEntidadFederativa>();
            this.LugarSolicitudRecurso = new HashSet<LugarSolicitudRecurso>();
        }
    
        public int catPaisID { get; set; }
        public string descripcion { get; set; }
        public Nullable<byte> tipoControl { get; set; }
        public bool estatusLogico { get; set; }
    
        public virtual ICollection<Agregaduria> Agregaduria { get; set; }
        public virtual ICollection<CatEntidadFederativa> CatEntidadFederativa { get; set; }
        public virtual ICollection<LugarSolicitudRecurso> LugarSolicitudRecurso { get; set; }
    }
}
