//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int facturaID { get; set; }
        public int proveedoresID { get; set; }
        public int monedaID { get; set; }
        public short estatusFacturaID { get; set; }
        public short cuentaProveedorID { get; set; }
        public string descripcionFactura { get; set; }
        public decimal montoFactura { get; set; }
        public string factura1 { get; set; }
        public string concepto { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> retencionIVA { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public Nullable<decimal> retencionISR { get; set; }
        public Nullable<decimal> deductiva { get; set; }
        public Nullable<decimal> tipoDeCambio { get; set; }
        public decimal total { get; set; }
    
        public virtual CatEstatusFactura CatEstatusFactura { get; set; }
        public virtual CatMoneda CatMoneda { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
