//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoAduana
    {
        public int gastoAduanaID { get; set; }
        public int solicitudRecursoID { get; set; }
        public int catAgenciaAduanalID { get; set; }
        public int catPartidaID { get; set; }
        public decimal importeSolicitado { get; set; }
    
        public virtual CatAgenciaAduanal CatAgenciaAduanal { get; set; }
        public virtual CatPartida CatPartida { get; set; }
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
    }
}
