//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoCheque
    {
        public int pagoChequeID { get; set; }
        public int movimientoAdministrativoID { get; set; }
        public short catEstausPagoID { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public string pagueseA { get; set; }
        public int numeroCheque { get; set; }
        public decimal importe { get; set; }
        public string numeroExpediente { get; set; }
    
        public virtual CatEstatusPago CatEstatusPago { get; set; }
        public virtual MovimientoAdministrativo MovimientoAdministrativo { get; set; }
    }
}
