//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaPago
    {
        public int polizaPagoID { get; set; }
        public int catPolizaID { get; set; }
        public short catPagoPolizaID { get; set; }
        public int pagoIdentificador { get; set; }
        public string numeroPoliza { get; set; }
        public System.DateTime fechaPoliza { get; set; }
    
        public virtual CatPagoPoliza CatPagoPoliza { get; set; }
        public virtual CatPoliza CatPoliza { get; set; }
    }
}
