//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Factura = new HashSet<Factura>();
            this.Penalizacion = new HashSet<Penalizacion>();
        }
    
        public int proveedorID { get; set; }
        public int solicitudRecursoID { get; set; }
        public int catPartidaID { get; set; }
        public int catMonedaID { get; set; }
        public int suficienciaPresupuestalID { get; set; }
        public string oficioRM { get; set; }
        public decimal importe { get; set; }
        public Nullable<decimal> tipoDeCambio { get; set; }
        public Nullable<decimal> total { get; set; }
        public bool anticipo { get; set; }
    
        public virtual CatMoneda CatMoneda { get; set; }
        public virtual CatPartida CatPartida { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Penalizacion> Penalizacion { get; set; }
        public virtual SolicitudRecurso SolicitudRecurso { get; set; }
    }
}
