//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIRFPROD_v2Entities : DbContext
    {
        public SIRFPROD_v2Entities()
            : base("name=SIRFPROD_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agregaduria> Agregaduria { get; set; }
        public DbSet<Asignacion> Asignacion { get; set; }
        public DbSet<Beca> Beca { get; set; }
        public DbSet<Becalos> Becalos { get; set; }
        public DbSet<Beneficiario> Beneficiario { get; set; }
        public DbSet<Bitacora> Bitacora { get; set; }
        public DbSet<CargaCuotaDiaria> CargaCuotaDiaria { get; set; }
        public DbSet<CatAcademia> CatAcademia { get; set; }
        public DbSet<CatAccion> CatAccion { get; set; }
        public DbSet<CatAgenciaAduanal> CatAgenciaAduanal { get; set; }
        public DbSet<CatArea> CatArea { get; set; }
        public DbSet<CatBanco> CatBanco { get; set; }
        public DbSet<CatConceptoGasto> CatConceptoGasto { get; set; }
        public DbSet<CatConceptoPago> CatConceptoPago { get; set; }
        public DbSet<CatCuenta> CatCuenta { get; set; }
        public DbSet<CatDependiente> CatDependiente { get; set; }
        public DbSet<CatDestino> CatDestino { get; set; }
        public DbSet<CatDocumento> CatDocumento { get; set; }
        public DbSet<CatEntidadFederativa> CatEntidadFederativa { get; set; }
        public DbSet<CatEstatusFactura> CatEstatusFactura { get; set; }
        public DbSet<CatEstatusPago> CatEstatusPago { get; set; }
        public DbSet<CatEstatusPresion> CatEstatusPresion { get; set; }
        public DbSet<CatEstatusSolicitud> CatEstatusSolicitud { get; set; }
        public DbSet<CatEvento> CatEvento { get; set; }
        public DbSet<CatEventoAccion> CatEventoAccion { get; set; }
        public DbSet<CatFirma> CatFirma { get; set; }
        public DbSet<CatFormaComprobacion> CatFormaComprobacion { get; set; }
        public DbSet<CatJefeDepto> CatJefeDepto { get; set; }
        public DbSet<CatModulo> CatModulo { get; set; }
        public DbSet<CatMoneda> CatMoneda { get; set; }
        public DbSet<CatMunicipio> CatMunicipio { get; set; }
        public DbSet<CatPago> CatPago { get; set; }
        public DbSet<CatPagoPoliza> CatPagoPoliza { get; set; }
        public DbSet<CatPais> CatPais { get; set; }
        public DbSet<CatPartida> CatPartida { get; set; }
        public DbSet<CatPerfil> CatPerfil { get; set; }
        public DbSet<CatPoliza> CatPoliza { get; set; }
        public DbSet<CatPrioridad> CatPrioridad { get; set; }
        public DbSet<CatRegion> CatRegion { get; set; }
        public DbSet<CatRol> CatRol { get; set; }
        public DbSet<CatSolicitud> CatSolicitud { get; set; }
        public DbSet<CatSubmodulo> CatSubmodulo { get; set; }
        public DbSet<CatUnidadAdm> CatUnidadAdm { get; set; }
        public DbSet<Clc> Clc { get; set; }
        public DbSet<DetalleSolicitudRecurso> DetalleSolicitudRecurso { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<EstatusAccion> EstatusAccion { get; set; }
        public DbSet<EstatusMovimiento> EstatusMovimiento { get; set; }
        public DbSet<EstatusPerfil> EstatusPerfil { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<FirmaElectronica> FirmaElectronica { get; set; }
        public DbSet<GastoAduana> GastoAduana { get; set; }
        public DbSet<GastoCorriente> GastoCorriente { get; set; }
        public DbSet<GastoFunerario> GastoFunerario { get; set; }
        public DbSet<Homologado> Homologado { get; set; }
        public DbSet<ImpuestoSobreNomina> ImpuestoSobreNomina { get; set; }
        public DbSet<Laudo> Laudo { get; set; }
        public DbSet<LogError> LogError { get; set; }
        public DbSet<LugarSolicitudRecurso> LugarSolicitudRecurso { get; set; }
        public DbSet<ModuloSubmodulo> ModuloSubmodulo { get; set; }
        public DbSet<MovimientoAdministrativo> MovimientoAdministrativo { get; set; }
        public DbSet<MovimientoBancario> MovimientoBancario { get; set; }
        public DbSet<PagoCheque> PagoCheque { get; set; }
        public DbSet<Parametro> Parametro { get; set; }
        public DbSet<PartidaSolicitudRecurso> PartidaSolicitudRecurso { get; set; }
        public DbSet<Penalizacion> Penalizacion { get; set; }
        public DbSet<PerfilModulo> PerfilModulo { get; set; }
        public DbSet<PolizaPago> PolizaPago { get; set; }
        public DbSet<PresionGasto> PresionGasto { get; set; }
        public DbSet<PresupuestoClc> PresupuestoClc { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<RegistroContable> RegistroContable { get; set; }
        public DbSet<RegistroVolante> RegistroVolante { get; set; }
        public DbSet<SolicitudCatUnidadAdm> SolicitudCatUnidadAdm { get; set; }
        public DbSet<SolicitudFirma> SolicitudFirma { get; set; }
        public DbSet<SolicitudRecurso> SolicitudRecurso { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoSolicitudPorArea> TipoSolicitudPorArea { get; set; }
        public DbSet<TipoSolicitudPorUA> TipoSolicitudPorUA { get; set; }
        public DbSet<TransferenciaBancaria> TransferenciaBancaria { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioRegionFiscalizacion> UsuarioRegionFiscalizacion { get; set; }
        public DbSet<AreaUnidadAdm> AreaUnidadAdm { get; set; }
        public DbSet<TipoJefeDepto> TipoJefeDepto { get; set; }
        public DbSet<vEstatusMovimientoBanco> vEstatusMovimientoBanco { get; set; }
        public DbSet<vwAsistentesEnlace> vwAsistentesEnlace { get; set; }
        public DbSet<vwBajaIntegrante> vwBajaIntegrante { get; set; }
        public DbSet<vwCentrosDeDistribucion> vwCentrosDeDistribucion { get; set; }
        public DbSet<vwCuentasIntegrante> vwCuentasIntegrante { get; set; }
        public DbSet<vwDatosIntegrante> vwDatosIntegrante { get; set; }
        public DbSet<vwDependientesIntegrante> vwDependientesIntegrante { get; set; }
        public DbSet<vwIncidenciasIntegrante> vwIncidenciasIntegrante { get; set; }
        public DbSet<vwTipoDependientesIntegrante> vwTipoDependientesIntegrante { get; set; }
    }
}
