//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCuentasIntegrante
    {
        public int cuentaIntegranteID { get; set; }
        public Nullable<int> expediente { get; set; }
        public string descripcionCuenta { get; set; }
        public string clabeInterbancaria { get; set; }
        public string descripcion { get; set; }
        public byte tipoCuentaID { get; set; }
        public string descripcionTipoCuenta { get; set; }
        public Nullable<bool> estatusLogico { get; set; }
    }
}
