//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIncidenciasIntegrante
    {
        public Nullable<int> expediente { get; set; }
        public string tipoIncidencia { get; set; }
        public Nullable<System.DateTime> fechaInicial { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
    }
}
